#pragma once

enum OpenSCADOperator {
	OPENSCAD_CARVE,	//add by Look
	OPENSCAD_UNION, 
	OPENSCAD_INTERSECTION, 
	OPENSCAD_DIFFERENCE, 
	OPENSCAD_MINKOWSKI,
	OPENSCAD_HULL,
	OPENSCAD_RESIZE,
	OPENSCAD_OUTLINE,
	OPENSCAD_APPEND
};
